fuel_per_km:
  cab: 8.0
  suv: 9.5
  mini-truck: 10.5
  truck: 12.0
distance_charge_per_km:
  cab: 8.0
  suv: 10.0
  mini-truck: 10.5
  truck: 12.0
driver_per_day:
  cab: 800
  suv: 900
  mini-truck: 1200
  truck: 1500
night_halt_per_night: 1000
food_per_day: 400
toll_per_100km: 100.0
gst_rate: 0.18

